import Anthropic from "@anthropic-ai/sdk";
import { ANTHROPIC_API_KEY } from "../env.js";
import buildSystemPrompt from "./system.prompt.js";

const client = new Anthropic({
    apiKey: ANTHROPIC_API_KEY
});


const streamAiResponse = (recent_context, streamResponse) => {
try {
const systemPrompt = buildSystemPrompt();

streamResponse("loadingStage", {stage: "Generating response..."});

const stream = client.messages.stream({
  model: "claude-haiku-4-5", //"claude-sonnet-4-5",
  system: systemPrompt,
    stream: true,
  max_tokens: 6024,
  messages: [...recent_context],
})

console.log("claude stream: ", stream);

// Need to return a Promise, so that chatController can await the stream to resolve and not end it prematurely
return new Promise((resolve, reject) => {
stream.on("text", (text) => {
        console.log("Text generated by Claude in controller", text);
        streamResponse("responseToken", text);
    });

stream.on("message", (message) => {
        streamResponse("done", message);
        resolve(message);
    });

stream.on("error", (error) => {
        streamResponse("error", error);
        reject(error);
    });
});
} catch (error) {
    throw error;
}
}

export default streamAiResponse;